export const INVOICES_LIST_REQUEST = "INVOICES_LIST_REQUEST"
export const INVOICES_LIST_SUCCESS = "INVOICES_LIST_SUCCESS"
export const INVOICES_LIST_FAIL = "INVOICES_LIST_FAIL"
export const FILTER_INVOICES_LIST = "FILTER_INVOICES_LIST"

